version: '3'

services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft
    volumes:
      - /opt/ftb_revelation:/data
    ports:
      - "25565:25565"
    tty: true
    stdin_open: true
    restart: always
    environment:
      EULA: "TRUE"
      DIFFICULTY: "hard"
      TYPE: "FTB"
      FTB_SERVER_MOD: "FTBRevelationServer_1.0.0.zip"
      MIN_RAM: "2G"
      MAX_RAM: "8G"